exports.readError = require("./read-error.js")
exports.readData = require("./read-latest.js")
exports.requestData = require("./request.js")
exports.whitelist = require("./whitelist")
exports.setOcrConfig = require("./setOcrConfig")
exports.manageAllowlist = require("./manageAllowlist")