/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v06 from "./v0.6";
export type { v06 };
import type * as v08 from "./v0.8";
export type { v08 };
