/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  VRFV2WrapperConsumerBase,
  VRFV2WrapperConsumerBaseInterface,
} from "../../../../../@chainlink/contracts/src/v0.8/VRFV2WrapperConsumerBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_requestId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "_randomWords",
        type: "uint256[]",
      },
    ],
    name: "rawFulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class VRFV2WrapperConsumerBase__factory {
  static readonly abi = _abi;
  static createInterface(): VRFV2WrapperConsumerBaseInterface {
    return new utils.Interface(_abi) as VRFV2WrapperConsumerBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VRFV2WrapperConsumerBase {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as VRFV2WrapperConsumerBase;
  }
}
